//! Opaque random tokens.
//!
//! Session identifiers, recovery codes, and one-time-code challenges are all
//! opaque values whose only property is being unguessable. They carry no
//! structure, are stored server-side, and are revocable.
//!
//! The default width is 256 bits rather than the 128-bit floor the design
//! document sets. The extra margin costs nothing — these are generated rarely
//! and compared by index — and it removes any need to revisit the question if
//! the threat model changes.

use rand::TryRng as _;
use rand::rngs::SysRng;
use std::fmt;

/// Bytes of entropy in a token generated by [`random_token`] with no explicit
/// width. 32 bytes is 256 bits.
pub const DEFAULT_TOKEN_BYTES: usize = 32;

/// An opaque random token.
#[derive(Clone, PartialEq, Eq)]
pub struct Token(Vec<u8>);

impl Token {
    /// The raw bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.0
    }

    /// Lowercase hex, for the form that goes in a cookie or a URL.
    #[must_use]
    pub fn to_hex(&self) -> String {
        hex::encode(&self.0)
    }
}

// A token in a log is a credential in a log.
impl fmt::Debug for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Token(<redacted, {} bytes>)", self.0.len())
    }
}

/// Generate a token of `bytes` bytes from the operating system's entropy
/// source.
///
/// # Panics
///
/// Panics if the operating system's random number generator fails. There is no
/// safe fallback: a token generated from a degraded source is worse than no
/// token, because it looks like a credential while being guessable.
///
/// # Examples
///
/// ```
/// use app_crypto::{DEFAULT_TOKEN_BYTES, random_token};
///
/// let token = random_token(DEFAULT_TOKEN_BYTES);
/// assert_eq!(token.bytes().len(), 32);
/// assert_ne!(token, random_token(DEFAULT_TOKEN_BYTES));
/// ```
#[must_use]
pub fn random_token(bytes: usize) -> Token {
    let mut buf = vec![0u8; bytes];
    SysRng
        .try_fill_bytes(&mut buf)
        .expect("operating system entropy source failed; refusing to issue a guessable token");
    Token(buf)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn tokens_are_the_requested_width() {
        assert_eq!(random_token(DEFAULT_TOKEN_BYTES).bytes().len(), 32);
        assert_eq!(random_token(8).bytes().len(), 8);
    }

    #[test]
    fn tokens_do_not_repeat() {
        let seen: HashSet<String> = (0..512).map(|_| random_token(32).to_hex()).collect();
        assert_eq!(seen.len(), 512, "a collision here means a broken generator");
    }

    #[test]
    fn tokens_are_not_trivially_constant() {
        // A generator returning all zeroes would pass a width check.
        assert!(random_token(32).bytes().iter().any(|&b| b != 0));
    }

    #[test]
    fn debug_does_not_leak_the_token() {
        let token = random_token(32);
        let rendered = format!("{token:?}");
        assert!(rendered.contains("redacted"));
        assert!(!rendered.contains(&token.to_hex()));
    }
}
